### PR TITLE
Rohithshan

### LINKED ISSUE #10: Additional functionality
Add the following list of functionality to the app:

- [ ] On enter or click the input value should disappear.

- [ ] When input is empty click or enter should not work.

- [ ] When you find the number you should not be able to click or enter. You can only give restart.

_Originally posted by @arundhishaan15 in https://github.com/arundhishaan15/guess-the-number-game/pull/9_

### LINKED ISSUE #11: HTML and CSS changes 1
- [ ] Change the title Guess a number from 1 to 100. Use a h2 tag and say 1>2>>>100 or 1--2---100

- [ ] You have to take the history out of the input div. When the history increases the input div also increases. Input div has to be fixed size.

- [ ] Add a heading called History while showing history.

- [ ] Add a stylish image border around history.

_Originally posted by @arundhishaan15 in https://github.com/arundhishaan15/guess-the-number-game/pull/9_

### LINKED ISSUE #12: CSS changes
- [ ] Change background from cover to fill.

```suggestion
body {
    margin: auto;
    background-image: url('images/image-asset.jpeg');
    background-size: fill;
```
or 
```suggestion
body {
    margin: auto;
    background-image: url('images/image-asset.jpeg');
    background-size: 100vw 700px;
```

_Originally posted by @arundhishaan15 in https://github.com/arundhishaan15/guess-the-number-game/pull/9_

### LINKED ISSUE #13: History title
- [ ] Get the result to the right on top of history.

_Originally posted by @arundhishaan15 in https://github.com/arundhishaan15/guess-the-number-game/pull/9_

### PR DESCRIPTION
**Pull request by Rohithshan**

### CODE REVIEW

File: script.js [hunk 1]
```diff
@@ -1,91 +1,127 @@
...
  * Guess The Number Game
- * TODO: Get user value from input and save it to variable numberGuess
- * TODO: Generate a random number 1 to 100 and save it to variable correctNumber
- * TODO: Console whether the guess is too high, too low, or is correct inside playGame function
- * TODO: Create a function called displayResult to move the logic for if the guess is too high, too low, or correct
- * TODO: Complete the showYouWon, showNumberAbove, showNumberBelow
- * TODO: Use the showYouWon... functions within displayResult to display the correct dialog
- * TODO: Save the guess history in a variable called guess
- * TODO: Display the guess history using displayHistory() function
- * TODO: Use the initGame() function to restart the game
```
Comment (arundhishaan15) [inline script.js]: Add the following list of functionality to the app:

- [x] On enter or click the input value should disappear.

- [x] When input is empty click or enter should not work.

- [x] When you find the number you should not be able to click or enter. You can only give restart.

File: index.html [hunk 2]
```diff
@@ -1,54 +1,36 @@
...
-        <!-- This is where the history will be -->
-      </div>
-    </main>
-  </body>
-</html>
+    <div class="row">
+        
+        <div class="side-title card">
+            <h1>Guess a number from 1 to 100</h1>
+            <div class="input-row" id="remove-input">
```
Comment (arundhishaan15) [inline index.html]: - [x] Change the title Guess a number from 1 to 100. Use a h2 tag and say 1>2>>>100 or 1--2---100

- [x] You have to take the history out of the input div. When the history increases the input div also increases. Input div has to be fixed size.

- [x] Add a heading called History while showing history.

- [x] Add a stylish image border around history.

File: style.css [hunk 3]
```diff
@@ -1,16 +1,85 @@
-#number-guess,
-#result,
-#history {
-  max-width: 400px;
-  margin: 0 auto;
+body {
+    margin: auto;
+    background-image: url('images/image-asset.jpeg');
+    background-size: cover;
```
Comment (arundhishaan15) [inline style.css]: - [x] Change background from cover to fill.

```suggestion
body {
    margin: auto;
    background-image: url('images/image-asset.jpeg');
    background-size: fill;
```
or 
```suggestion
body {
    margin: auto;
    background-image: url('images/image-asset.jpeg');
    background-size: 100vw 700px;
```

File: style.css [hunk 4]
```diff
@@ -1,16 +1,85 @@
...
+.card {
+    background-color: cadetblue;
+}
+
+#result {
+    width: 770px;
+    padding: 10px;
+    padding-left: 45px;
+    align-items: flex-start;
+
```
Comment (arundhishaan15) [inline style.css]: - [x] Get the result to the right on top of history.

**Review by arundhishaan15 — CHANGES_REQUESTED** [review]
@Rohithshan Please make the necessary changes. 
Please go to nidhushan branch on your VS code using git checkout command and check his files if you are stuck. If it didn't work out then ask Nidhushan.

File: script.js (hunk 1 above)
Comment (arundhishaan15) [reply script.js]: First two tasks are done. Check the third task. Once you got the final result you are still able to input a number.

File: index.html (hunk 2 above)
Comment (arundhishaan15) [reply index.html]: Can you check if the heading is h2 or can you make the heading on the first task a bit bigger?

File: index.html [hunk 5]
```diff
@@ -1,54 +1,42 @@
...
-  </head>
-  <body class="text-center">
+</head>
+<body class="text-center">
+
     <nav class="navbar navbar-dark bg-dark">
-      <!-- Navigation bar content -->
-      <a class="navbar-brand" href="#">Guess The Number</a>
+        <!-- Navbar content -->
+        <a class="navbar-brand" href="#"><h1>Guess The Number</h1></a>
```
Comment (arundhishaan15) [inline index.html]: - [ ] Try to reduce the banner font size of Guess the Number by 1 or 2. It is too big.

File: script.js (hunk 1 above)
Comment (arundhishaan15) [reply script.js]: - [x] Your code is not resetting everything properly once you click restart. Please check that.

**Review by arundhishaan15 — COMMENTED** [review]
Please check for further changes.

**Review by arundhishaan15 — APPROVED** [review]
Nice work!
